### ROOT

GET http://localhost:4000/api/v1/ HTTP/1.1
Content-Type: application/json

### PRODUCTS

### GetMany

GET http://localhost:4000/api/v1/products HTTP/1.1
Content-Type: application/json

### GetOne

GET http://localhost:4000/api/v1/products/1 HTTP/1.1
Content-Type: application/json


### Create

POST http://localhost:4000/api/v1/products HTTP/1.1
Content-Type: application/json

{
    "name": "New Product",
    "description": "New Description",
    "price": 19.99,
    "stock": 100,
    "categoryId": 1
}


### Update

PUT http://localhost:4000/api/v1/products/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Product",
    "description": "Updated Description",
    "price": 24.99,
    "stock": 50,
    "categoryId": 1
}

### Delete

DELETE http://localhost:4000/api/v1/products/4 HTTP/1.1
Content-Type: application/json
